// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using letiahomes.Infrastructure.Data;

#nullable disable

namespace letiahomes.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260501152501_DataSeeding")]
    partial class DataSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LandlordProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AppUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId")
                        .IsUnique();

                    b.ToTable("LandlordProfiles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-5678-90ab-cdef-111111111111"),
                            AppUserId = "e5f6a7b8-c9d0-1234-efab-456789012346",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsVerified = true
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-6789-01bc-def0-222222222222"),
                            AppUserId = "f6a7b8c9-d0e1-2345-fabc-567890123457",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsVerified = true
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                            ConcurrencyStamp = "f1e2d3c4-b5a6-7890-abcd-ef0987654321",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "c3d4e5f6-a7b8-9012-cdef-234567890123",
                            ConcurrencyStamp = "e5f6a7b8-c9d0-1234-efab-456789012345",
                            Name = "Landlord",
                            NormalizedName = "LANDLORD"
                        },
                        new
                        {
                            Id = "d4e5f6a7-b8c9-0123-defa-345678901234",
                            ConcurrencyStamp = "f6a7b8c9-d0e1-2345-fabc-567890123456",
                            Name = "Tenant",
                            NormalizedName = "TENANT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "b2c3d4e5-f6a7-8901-bcde-f12345678901",
                            RoleId = "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
                        },
                        new
                        {
                            UserId = "e5f6a7b8-c9d0-1234-efab-456789012346",
                            RoleId = "c3d4e5f6-a7b8-9012-cdef-234567890123"
                        },
                        new
                        {
                            UserId = "f6a7b8c9-d0e1-2345-fabc-567890123457",
                            RoleId = "c3d4e5f6-a7b8-9012-cdef-234567890123"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("letiahomes.Domain.Entities.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "b2c3d4e5-f6a7-8901-bcde-f12345678901",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d4e5f6a7-b8c9-0123-defa-234567890123",
                            CreatedAt = new DateTime(2026, 5, 1, 15, 24, 59, 606, DateTimeKind.Utc).AddTicks(9861),
                            Email = "gbolahanagbeleye@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Inioluwa",
                            IsActive = true,
                            IsVerified = true,
                            LastName = "Agbeleye",
                            LockoutEnabled = false,
                            NormalizedEmail = "GBOLAHANAGBELEYE@GMAIL.COM",
                            NormalizedUserName = "GBOLAHANAGBELEYE@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEMcur/vuEm1fcovJUc0Yp6WPPpTxPyUXZN7hB+PLbFrYpqSRmdP93tJ3fnV+CnoZMg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c3d4e5f6-a7b8-9012-cdef-123456789012",
                            TwoFactorEnabled = false,
                            UserName = "gbolahanagbeleye@gmail.com"
                        },
                        new
                        {
                            Id = "e5f6a7b8-c9d0-1234-efab-456789012346",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b2c3d4e5-f6a7-8901-bcde-111111111111",
                            CreatedAt = new DateTime(2026, 5, 1, 15, 24, 59, 712, DateTimeKind.Utc).AddTicks(3992),
                            Email = "emeka.obi@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Chukwuemeka",
                            IsActive = true,
                            IsVerified = true,
                            LastName = "Obi",
                            LockoutEnabled = false,
                            NormalizedEmail = "EMEKA.OBI@GMAIL.COM",
                            NormalizedUserName = "EMEKA.OBI@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEEV08s9NTzQgNShR9SbNfmyjtGQs+3Gf6tpwsztzlQtsBUEoqw1zHuENvnUeWTV08g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a1b2c3d4-e5f6-7890-abcd-111111111111",
                            TwoFactorEnabled = false,
                            UserName = "emeka.obi@gmail.com"
                        },
                        new
                        {
                            Id = "f6a7b8c9-d0e1-2345-fabc-567890123457",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d4e5f6a7-b8c9-0123-defa-222222222222",
                            CreatedAt = new DateTime(2026, 5, 1, 15, 24, 59, 819, DateTimeKind.Utc).AddTicks(3958),
                            Email = "amara.nwosu@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Amara",
                            IsActive = true,
                            IsVerified = true,
                            LastName = "Nwosu",
                            LockoutEnabled = false,
                            NormalizedEmail = "AMARA.NWOSU@GMAIL.COM",
                            NormalizedUserName = "AMARA.NWOSU@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELnaRXBMk6PvalsH4vbJZ4Nuhu0HJhL/7NCwBmVNfeNoLaA9Z4e6NB29hCpWiEZKMw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c3d4e5f6-a7b8-9012-cdef-222222222222",
                            TwoFactorEnabled = false,
                            UserName = "amara.nwosu@gmail.com"
                        });
                });

            modelBuilder.Entity("letiahomes.Domain.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CheckIn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CheckOut")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NumberOfGuests")
                        .HasColumnType("integer");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantProfileId")
                        .HasColumnType("uuid");

                    b.Property<long>("TotalAmountKobo")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.HasIndex("TenantProfileId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("letiahomes.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("AmountKobo")
                        .HasColumnType("bigint");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaystackReference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("letiahomes.Domain.Entities.Payout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("AmountKobo")
                        .HasColumnType("bigint");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LandlordProfileId")
                        .HasColumnType("uuid");

                    b.Property<long>("PlatformFeeKobo")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LandlordProfileId");

                    b.ToTable("Payouts");
                });

            modelBuilder.Entity("letiahomes.Domain.Entities.Property", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Bathrooms")
                        .HasColumnType("integer");

                    b.Property<int>("Bedrooms")
                        .HasColumnType("integer");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LandlordProfileId")
                        .HasColumnType("uuid");

                    b.Property<int>("ListingType")
                        .HasColumnType("integer");

                    b.Property<int>("MaxGuests")
                        .HasColumnType("integer");

                    b.Property<long>("PricePerNightKobo")
                        .HasColumnType("bigint");

                    b.Property<int>("PropertyType")
                        .HasColumnType("integer");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LandlordProfileId");

                    b.ToTable("Properties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c1d2e3f4-1234-5678-abcd-aaaaaaaaaaaa"),
                            Address = "15 Admiralty Way",
                            Bathrooms = 3,
                            Bedrooms = 3,
                            City = "Lagos",
                            Country = "Nigeria",
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A stunning fully furnished apartment with ocean views, 24/7 power supply, and top-tier security. Perfect for business travellers and families.",
                            IsApproved = true,
                            IsAvailable = true,
                            LandlordProfileId = new Guid("a1b2c3d4-5678-90ab-cdef-111111111111"),
                            ListingType = 1,
                            MaxGuests = 6,
                            PricePerNightKobo = 7500000L,
                            PropertyType = 0,
                            State = "Lagos",
                            Title = "Luxury 3-Bedroom Apartment in Lekki Phase 1"
                        },
                        new
                        {
                            Id = new Guid("c2d3e4f5-2345-6789-bcde-bbbbbbbbbbbb"),
                            Address = "42 Adeola Odeku Street",
                            Bathrooms = 1,
                            Bedrooms = 1,
                            City = "Lagos",
                            Country = "Nigeria",
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A sleek, compact studio ideal for solo business travellers. Walking distance to major banks, restaurants, and the Lagos business district.",
                            IsApproved = true,
                            IsAvailable = true,
                            LandlordProfileId = new Guid("a1b2c3d4-5678-90ab-cdef-111111111111"),
                            ListingType = 1,
                            MaxGuests = 2,
                            PricePerNightKobo = 3500000L,
                            PropertyType = 1,
                            State = "Lagos",
                            Title = "Modern Studio in Victoria Island"
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-3456-789a-cdef-cccccccccccc"),
                            Address = "8 Mobolaji Johnson Avenue",
                            Bathrooms = 4,
                            Bedrooms = 4,
                            City = "Lagos",
                            Country = "Nigeria",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A beautifully maintained 4-bedroom duplex in the serene Ikeja GRA. Comes with a private pool, generator, and dedicated parking for 3 cars.",
                            IsApproved = true,
                            IsAvailable = true,
                            LandlordProfileId = new Guid("a1b2c3d4-5678-90ab-cdef-111111111111"),
                            ListingType = 1,
                            MaxGuests = 8,
                            PricePerNightKobo = 12000000L,
                            PropertyType = 2,
                            State = "Lagos",
                            Title = "Spacious Duplex in Ikeja GRA"
                        },
                        new
                        {
                            Id = new Guid("c4d5e6f7-4567-89ab-def0-dddddddddddd"),
                            Address = "23 Aminu Kano Crescent",
                            Bathrooms = 1,
                            Bedrooms = 1,
                            City = "Abuja",
                            Country = "Nigeria",
                            CreatedAt = new DateTime(2026, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A clean, well-maintained self-contain apartment in the heart of Wuse 2. Great for short stays in Abuja with easy access to major roads.",
                            IsApproved = true,
                            IsAvailable = true,
                            LandlordProfileId = new Guid("b2c3d4e5-6789-01bc-def0-222222222222"),
                            ListingType = 1,
                            MaxGuests = 2,
                            PricePerNightKobo = 2500000L,
                            PropertyType = 7,
                            State = "FCT",
                            Title = "Cosy Self-Contain in Wuse 2"
                        },
                        new
                        {
                            Id = new Guid("c5d6e7f8-5678-9abc-ef01-eeeeeeeeeeee"),
                            Address = "5 Gana Street",
                            Bathrooms = 3,
                            Bedrooms = 3,
                            City = "Abuja",
                            Country = "Nigeria",
                            CreatedAt = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A breathtaking penthouse with panoramic views of Abuja. Floor-to-ceiling windows, a rooftop terrace, and premium finishes throughout.",
                            IsApproved = true,
                            IsAvailable = true,
                            LandlordProfileId = new Guid("b2c3d4e5-6789-01bc-def0-222222222222"),
                            ListingType = 1,
                            MaxGuests = 6,
                            PricePerNightKobo = 25000000L,
                            PropertyType = 6,
                            State = "FCT",
                            Title = "Executive Penthouse in Maitama"
                        },
                        new
                        {
                            Id = new Guid("c6d7e8f9-6789-abcd-f012-ffffffffffff"),
                            Address = "12 Peter Odili Road",
                            Bathrooms = 2,
                            Bedrooms = 2,
                            City = "Port Harcourt",
                            Country = "Nigeria",
                            CreatedAt = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A tastefully furnished 2-bedroom bungalow in New GRA. Quiet neighbourhood, 24-hour security, and close to major shopping centres.",
                            IsApproved = true,
                            IsAvailable = true,
                            LandlordProfileId = new Guid("b2c3d4e5-6789-01bc-def0-222222222222"),
                            ListingType = 1,
                            MaxGuests = 4,
                            PricePerNightKobo = 4500000L,
                            PropertyType = 4,
                            State = "Rivers",
                            Title = "Charming Bungalow in New GRA Port Harcourt"
                        });
                });

            modelBuilder.Entity("letiahomes.Domain.Entities.PropertyAmenity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("PropertyAmenities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e1000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "WiFi",
                            PropertyId = new Guid("c1d2e3f4-1234-5678-abcd-aaaaaaaaaaaa")
                        },
                        new
                        {
                            Id = new Guid("e1000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Air Conditioning",
                            PropertyId = new Guid("c1d2e3f4-1234-5678-abcd-aaaaaaaaaaaa")
                        },
                        new
                        {
                            Id = new Guid("e1000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "24hr Generator",
                            PropertyId = new Guid("c1d2e3f4-1234-5678-abcd-aaaaaaaaaaaa")
                        },
                        new
                        {
                            Id = new Guid("e1000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Security",
                            PropertyId = new Guid("c1d2e3f4-1234-5678-abcd-aaaaaaaaaaaa")
                        },
                        new
                        {
                            Id = new Guid("e1000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Parking",
                            PropertyId = new Guid("c1d2e3f4-1234-5678-abcd-aaaaaaaaaaaa")
                        },
                        new
                        {
                            Id = new Guid("e2000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "WiFi",
                            PropertyId = new Guid("c2d3e4f5-2345-6789-bcde-bbbbbbbbbbbb")
                        },
                        new
                        {
                            Id = new Guid("e2000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Air Conditioning",
                            PropertyId = new Guid("c2d3e4f5-2345-6789-bcde-bbbbbbbbbbbb")
                        },
                        new
                        {
                            Id = new Guid("e2000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "24hr Generator",
                            PropertyId = new Guid("c2d3e4f5-2345-6789-bcde-bbbbbbbbbbbb")
                        },
                        new
                        {
                            Id = new Guid("e3000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Swimming Pool",
                            PropertyId = new Guid("c3d4e5f6-3456-789a-cdef-cccccccccccc")
                        },
                        new
                        {
                            Id = new Guid("e3000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "WiFi",
                            PropertyId = new Guid("c3d4e5f6-3456-789a-cdef-cccccccccccc")
                        },
                        new
                        {
                            Id = new Guid("e3000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Air Conditioning",
                            PropertyId = new Guid("c3d4e5f6-3456-789a-cdef-cccccccccccc")
                        },
                        new
                        {
                            Id = new Guid("e3000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "24hr Generator",
                            PropertyId = new Guid("c3d4e5f6-3456-789a-cdef-cccccccccccc")
                        },
                        new
                        {
                            Id = new Guid("e3000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Gym",
                            PropertyId = new Guid("c3d4e5f6-3456-789a-cdef-cccccccccccc")
                        },
                        new
                        {
                            Id = new Guid("e4000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "WiFi",
                            PropertyId = new Guid("c4d5e6f7-4567-89ab-def0-dddddddddddd")
                        },
                        new
                        {
                            Id = new Guid("e4000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Air Conditioning",
                            PropertyId = new Guid("c4d5e6f7-4567-89ab-def0-dddddddddddd")
                        },
                        new
                        {
                            Id = new Guid("e4000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Security",
                            PropertyId = new Guid("c4d5e6f7-4567-89ab-def0-dddddddddddd")
                        },
                        new
                        {
                            Id = new Guid("e5000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Rooftop Terrace",
                            PropertyId = new Guid("c5d6e7f8-5678-9abc-ef01-eeeeeeeeeeee")
                        },
                        new
                        {
                            Id = new Guid("e5000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "WiFi",
                            PropertyId = new Guid("c5d6e7f8-5678-9abc-ef01-eeeeeeeeeeee")
                        },
                        new
                        {
                            Id = new Guid("e5000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Air Conditioning",
                            PropertyId = new Guid("c5d6e7f8-5678-9abc-ef01-eeeeeeeeeeee")
                        },
                        new
                        {
                            Id = new Guid("e5000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Concierge Service",
                            PropertyId = new Guid("c5d6e7f8-5678-9abc-ef01-eeeeeeeeeeee")
                        },
                        new
                        {
                            Id = new Guid("e5000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "24hr Generator",
                            PropertyId = new Guid("c5d6e7f8-5678-9abc-ef01-eeeeeeeeeeee")
                        },
                        new
                        {
                            Id = new Guid("e6000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "WiFi",
                            PropertyId = new Guid("c6d7e8f9-6789-abcd-f012-ffffffffffff")
                        },
                        new
                        {
                            Id = new Guid("e6000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Parking",
                            PropertyId = new Guid("c6d7e8f9-6789-abcd-f012-ffffffffffff")
                        },
                        new
                        {
                            Id = new Guid("e6000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Security",
                            PropertyId = new Guid("c6d7e8f9-6789-abcd-f012-ffffffffffff")
                        },
                        new
                        {
                            Id = new Guid("e6000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Air Conditioning",
                            PropertyId = new Guid("c6d7e8f9-6789-abcd-f012-ffffffffffff")
                        });
                });

            modelBuilder.Entity("letiahomes.Domain.Entities.PropertyImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsCoverImage")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("PropertyImages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d1000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80",
                            IsCoverImage = true,
                            PropertyId = new Guid("c1d2e3f4-1234-5678-abcd-aaaaaaaaaaaa"),
                            PublicId = ""
                        },
                        new
                        {
                            Id = new Guid("d1000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80",
                            IsCoverImage = false,
                            PropertyId = new Guid("c1d2e3f4-1234-5678-abcd-aaaaaaaaaaaa"),
                            PublicId = ""
                        },
                        new
                        {
                            Id = new Guid("d1000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800&q=80",
                            IsCoverImage = false,
                            PropertyId = new Guid("c1d2e3f4-1234-5678-abcd-aaaaaaaaaaaa"),
                            PublicId = ""
                        },
                        new
                        {
                            Id = new Guid("d2000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80",
                            IsCoverImage = true,
                            PropertyId = new Guid("c2d3e4f5-2345-6789-bcde-bbbbbbbbbbbb"),
                            PublicId = ""
                        },
                        new
                        {
                            Id = new Guid("d2000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=800&q=80",
                            IsCoverImage = false,
                            PropertyId = new Guid("c2d3e4f5-2345-6789-bcde-bbbbbbbbbbbb"),
                            PublicId = ""
                        },
                        new
                        {
                            Id = new Guid("d3000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&q=80",
                            IsCoverImage = true,
                            PropertyId = new Guid("c3d4e5f6-3456-789a-cdef-cccccccccccc"),
                            PublicId = ""
                        },
                        new
                        {
                            Id = new Guid("d3000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80",
                            IsCoverImage = false,
                            PropertyId = new Guid("c3d4e5f6-3456-789a-cdef-cccccccccccc"),
                            PublicId = ""
                        },
                        new
                        {
                            Id = new Guid("d3000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1576941089067-2de3c901e126?w=800&q=80",
                            IsCoverImage = false,
                            PropertyId = new Guid("c3d4e5f6-3456-789a-cdef-cccccccccccc"),
                            PublicId = ""
                        },
                        new
                        {
                            Id = new Guid("d4000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1554995207-c18c203602cb?w=800&q=80",
                            IsCoverImage = true,
                            PropertyId = new Guid("c4d5e6f7-4567-89ab-def0-dddddddddddd"),
                            PublicId = ""
                        },
                        new
                        {
                            Id = new Guid("d4000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&q=80",
                            IsCoverImage = false,
                            PropertyId = new Guid("c4d5e6f7-4567-89ab-def0-dddddddddddd"),
                            PublicId = ""
                        },
                        new
                        {
                            Id = new Guid("d5000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80",
                            IsCoverImage = true,
                            PropertyId = new Guid("c5d6e7f8-5678-9abc-ef01-eeeeeeeeeeee"),
                            PublicId = ""
                        },
                        new
                        {
                            Id = new Guid("d5000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1560185007-cde436f6a4d0?w=800&q=80",
                            IsCoverImage = false,
                            PropertyId = new Guid("c5d6e7f8-5678-9abc-ef01-eeeeeeeeeeee"),
                            PublicId = ""
                        },
                        new
                        {
                            Id = new Guid("d5000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80",
                            IsCoverImage = false,
                            PropertyId = new Guid("c5d6e7f8-5678-9abc-ef01-eeeeeeeeeeee"),
                            PublicId = ""
                        },
                        new
                        {
                            Id = new Guid("d6000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&q=80",
                            IsCoverImage = true,
                            PropertyId = new Guid("c6d7e8f9-6789-abcd-f012-ffffffffffff"),
                            PublicId = ""
                        },
                        new
                        {
                            Id = new Guid("d6000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800&q=80",
                            IsCoverImage = false,
                            PropertyId = new Guid("c6d7e8f9-6789-abcd-f012-ffffffffffff"),
                            PublicId = ""
                        });
                });

            modelBuilder.Entity("letiahomes.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("letiahomes.Domain.Entities.TenantProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AppUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId")
                        .IsUnique();

                    b.ToTable("TenantProfiles");
                });

            modelBuilder.Entity("letiahomes.Domain.Entities.UnavailableDate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("UnavailableDates");
                });

            modelBuilder.Entity("LandlordProfile", b =>
                {
                    b.HasOne("letiahomes.Domain.Entities.AppUser", "AppUser")
                        .WithOne()
                        .HasForeignKey("LandlordProfile", "AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("letiahomes.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("letiahomes.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("letiahomes.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("letiahomes.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("letiahomes.Domain.Entities.Booking", b =>
                {
                    b.HasOne("letiahomes.Domain.Entities.Property", "Property")
                        .WithMany("Bookings")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("letiahomes.Domain.Entities.TenantProfile", "Tenant")
                        .WithMany("Bookings")
                        .HasForeignKey("TenantProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Property");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("letiahomes.Domain.Entities.Payment", b =>
                {
                    b.HasOne("letiahomes.Domain.Entities.Booking", "Booking")
                        .WithOne("Payment")
                        .HasForeignKey("letiahomes.Domain.Entities.Payment", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("letiahomes.Domain.Entities.Payout", b =>
                {
                    b.HasOne("LandlordProfile", "Landlord")
                        .WithMany("Payouts")
                        .HasForeignKey("LandlordProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Landlord");
                });

            modelBuilder.Entity("letiahomes.Domain.Entities.Property", b =>
                {
                    b.HasOne("LandlordProfile", "Landlord")
                        .WithMany("Properties")
                        .HasForeignKey("LandlordProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Landlord");
                });

            modelBuilder.Entity("letiahomes.Domain.Entities.PropertyAmenity", b =>
                {
                    b.HasOne("letiahomes.Domain.Entities.Property", "Property")
                        .WithMany("Amenities")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("letiahomes.Domain.Entities.PropertyImage", b =>
                {
                    b.HasOne("letiahomes.Domain.Entities.Property", "Property")
                        .WithMany("Images")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("letiahomes.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("letiahomes.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("letiahomes.Domain.Entities.TenantProfile", b =>
                {
                    b.HasOne("letiahomes.Domain.Entities.AppUser", "AppUser")
                        .WithOne()
                        .HasForeignKey("letiahomes.Domain.Entities.TenantProfile", "AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("letiahomes.Domain.Entities.UnavailableDate", b =>
                {
                    b.HasOne("letiahomes.Domain.Entities.Property", "Property")
                        .WithMany("UnavailableDates")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("LandlordProfile", b =>
                {
                    b.Navigation("Payouts");

                    b.Navigation("Properties");
                });

            modelBuilder.Entity("letiahomes.Domain.Entities.Booking", b =>
                {
                    b.Navigation("Payment");
                });

            modelBuilder.Entity("letiahomes.Domain.Entities.Property", b =>
                {
                    b.Navigation("Amenities");

                    b.Navigation("Bookings");

                    b.Navigation("Images");

                    b.Navigation("UnavailableDates");
                });

            modelBuilder.Entity("letiahomes.Domain.Entities.TenantProfile", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
